begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|bcel
operator|.
name|verifier
operator|.
name|structurals
package|;
end_package

begin_comment
comment|/* ====================================================================  * The Apache Software License, Version 1.1  *  * Copyright (c) 2001 The Apache Software Foundation.  All rights  * reserved.  *  * Redistribution and use in source and binary forms, with or without  * modification, are permitted provided that the following conditions  * are met:  *  * 1. Redistributions of source code must retain the above copyright  *    notice, this list of conditions and the following disclaimer.  *  * 2. Redistributions in binary form must reproduce the above copyright  *    notice, this list of conditions and the following disclaimer in  *    the documentation and/or other materials provided with the  *    distribution.  *  * 3. The end-user documentation included with the redistribution,  *    if any, must include the following acknowledgment:  *       "This product includes software developed by the  *        Apache Software Foundation (http://www.apache.org/)."  *    Alternately, this acknowledgment may appear in the software itself,  *    if and wherever such third-party acknowledgments normally appear.  *  * 4. The names "Apache" and "Apache Software Foundation" and  *    "Apache BCEL" must not be used to endorse or promote products  *    derived from this software without prior written permission. For  *    written permission, please contact apache@apache.org.  *  * 5. Products derived from this software may not be called "Apache",  *    "Apache BCEL", nor may "Apache" appear in their name, without  *    prior written permission of the Apache Software Foundation.  *  * THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESSED OR IMPLIED  * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES  * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE  * DISCLAIMED.  IN NO EVENT SHALL THE APACHE SOFTWARE FOUNDATION OR  * ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,  * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT  * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF  * USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND  * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,  * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT  * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF  * SUCH DAMAGE.  * ====================================================================  *  * This software consists of voluntary contributions made by many  * individuals on behalf of the Apache Software Foundation.  For more  * information on the Apache Software Foundation, please see  *<http://www.apache.org/>.  */
end_comment

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|bcel
operator|.
name|Constants
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|bcel
operator|.
name|Repository
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|bcel
operator|.
name|generic
operator|.
name|*
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|bcel
operator|.
name|classfile
operator|.
name|JavaClass
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|bcel
operator|.
name|classfile
operator|.
name|Constant
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|bcel
operator|.
name|classfile
operator|.
name|ConstantDouble
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|bcel
operator|.
name|classfile
operator|.
name|ConstantFloat
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|bcel
operator|.
name|classfile
operator|.
name|ConstantInteger
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|bcel
operator|.
name|classfile
operator|.
name|ConstantLong
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|bcel
operator|.
name|classfile
operator|.
name|ConstantString
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|bcel
operator|.
name|verifier
operator|.
name|Verifier
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|bcel
operator|.
name|verifier
operator|.
name|exc
operator|.
name|*
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|ArrayList
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Hashtable
import|;
end_import

begin_comment
comment|/**  * This Visitor class may be used for a type-based Java Virtual Machine  * simulation.  * It does not check for correct types on the OperandStack or in the  * LocalVariables; nor does it check their sizes are sufficiently big.  * Thus, to use this Visitor for bytecode verifying, you have to make sure  * externally that the type constraints of the Java Virtual Machine instructions  * are satisfied. An InstConstraintVisitor may be used for this.  * Anyway, this Visitor does not mandate it. For example, when you  * visitIADD(IADD o), then there are two stack slots popped and one  * stack slot containing a Type.INT is pushed (where you could also  * pop only one slot if you know there are two Type.INT on top of the  * stack). Monitor-specific behaviour is not simulated.  *   *</P><B>Conventions:</B>  *  * Type.VOID will never be pushed onto the stack. Type.DOUBLE and Type.LONG  * that would normally take up two stack slots (like Double_HIGH and  * Double_LOW) are represented by a simple single Type.DOUBLE or Type.LONG  * object on the stack here.  * If a two-slot type is stored into a local variable, the next variable  * is given the type Type.UNKNOWN.  *  * @version $Id$  * @author<A HREF="http://www.inf.fu-berlin.de/~ehaase"/>Enver Haase</A>  * @see #visitDSTORE(DSTORE o)  * @see InstConstraintVisitor  */
end_comment

begin_class
specifier|public
class|class
name|ExecutionVisitor
extends|extends
name|EmptyVisitor
implements|implements
name|Visitor
block|{
comment|/** 	 * The executionframe we're operating on. 	 */
specifier|private
name|Frame
name|frame
init|=
literal|null
decl_stmt|;
comment|/** 	 * The ConstantPoolGen we're working with. 	 * @see #setConstantPoolGen(ConstantPoolGen) 	 */
specifier|private
name|ConstantPoolGen
name|cpg
init|=
literal|null
decl_stmt|;
comment|/** 	 * Constructor. Constructs a new instance of this class. 	 */
specifier|public
name|ExecutionVisitor
parameter_list|()
block|{
block|}
comment|/** 	 * The OperandStack from the current Frame we're operating on. 	 * @see #setFrame(Frame) 	 */
specifier|private
name|OperandStack
name|stack
parameter_list|()
block|{
return|return
name|frame
operator|.
name|getStack
argument_list|()
return|;
block|}
comment|/** 	 * The LocalVariables from the current Frame we're operating on. 	 * @see #setFrame(Frame) 	 */
specifier|private
name|LocalVariables
name|locals
parameter_list|()
block|{
return|return
name|frame
operator|.
name|getLocals
argument_list|()
return|;
block|}
comment|/** 	 * Sets the ConstantPoolGen needed for symbolic execution. 	 */
specifier|public
name|void
name|setConstantPoolGen
parameter_list|(
name|ConstantPoolGen
name|cpg
parameter_list|)
block|{
name|this
operator|.
name|cpg
operator|=
name|cpg
expr_stmt|;
block|}
comment|/** 	 * The only method granting access to the single instance of 	 * the ExecutionVisitor class. Before actively using this 	 * instance,<B>SET THE ConstantPoolGen FIRST</B>. 	 * @see #setConstantPoolGen(ConstantPoolGen) 	 */
specifier|public
name|void
name|setFrame
parameter_list|(
name|Frame
name|f
parameter_list|)
block|{
name|this
operator|.
name|frame
operator|=
name|f
expr_stmt|;
block|}
comment|///** Symbolically executes the corresponding Java Virtual Machine instruction. */
comment|//public void visitWIDE(WIDE o){
comment|// The WIDE instruction is modelled as a flag
comment|// of the embedded instructions in BCEL.
comment|// Therefore BCEL checks for possible errors
comment|// when parsing in the .class file: We don't
comment|// have even the possibilty to care for WIDE
comment|// here.
comment|//}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitAALOAD
parameter_list|(
name|AALOAD
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
comment|// pop the index int
comment|//System.out.print(stack().peek());
name|Type
name|t
init|=
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
decl_stmt|;
comment|// Pop Array type
if|if
condition|(
name|t
operator|==
name|Type
operator|.
name|NULL
condition|)
block|{
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|NULL
argument_list|)
expr_stmt|;
block|}
comment|// Do nothing stackwise --- a NullPointerException is thrown at Run-Time
else|else
block|{
name|ArrayType
name|at
init|=
operator|(
name|ArrayType
operator|)
name|t
decl_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|at
operator|.
name|getElementType
argument_list|()
argument_list|)
expr_stmt|;
block|}
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitAASTORE
parameter_list|(
name|AASTORE
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitACONST_NULL
parameter_list|(
name|ACONST_NULL
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|NULL
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitALOAD
parameter_list|(
name|ALOAD
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|locals
argument_list|()
operator|.
name|get
argument_list|(
name|o
operator|.
name|getIndex
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitANEWARRAY
parameter_list|(
name|ANEWARRAY
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
comment|//count
name|stack
argument_list|()
operator|.
name|push
argument_list|(
operator|new
name|ArrayType
argument_list|(
name|o
operator|.
name|getType
argument_list|(
name|cpg
argument_list|)
argument_list|,
literal|1
argument_list|)
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitARETURN
parameter_list|(
name|ARETURN
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitARRAYLENGTH
parameter_list|(
name|ARRAYLENGTH
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|INT
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitASTORE
parameter_list|(
name|ASTORE
name|o
parameter_list|)
block|{
name|locals
argument_list|()
operator|.
name|set
argument_list|(
name|o
operator|.
name|getIndex
argument_list|()
argument_list|,
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
argument_list|)
expr_stmt|;
comment|//System.err.println("TODO-DEBUG:	set LV '"+o.getIndex()+"' to '"+locals().get(o.getIndex())+"'.");
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitATHROW
parameter_list|(
name|ATHROW
name|o
parameter_list|)
block|{
name|Type
name|t
init|=
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
decl_stmt|;
name|stack
argument_list|()
operator|.
name|clear
argument_list|()
expr_stmt|;
if|if
condition|(
name|t
operator|.
name|equals
argument_list|(
name|Type
operator|.
name|NULL
argument_list|)
condition|)
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|getType
argument_list|(
literal|"Ljava/lang/NullPointerException;"
argument_list|)
argument_list|)
expr_stmt|;
else|else
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|t
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitBALOAD
parameter_list|(
name|BALOAD
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|INT
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitBASTORE
parameter_list|(
name|BASTORE
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitBIPUSH
parameter_list|(
name|BIPUSH
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|INT
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitCALOAD
parameter_list|(
name|CALOAD
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|INT
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitCASTORE
parameter_list|(
name|CASTORE
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitCHECKCAST
parameter_list|(
name|CHECKCAST
name|o
parameter_list|)
block|{
comment|// It's possibly wrong to do so, but SUN's
comment|// ByteCode verifier seems to do (only) this, too.
comment|// TODO: One could use a sophisticated analysis here to check
comment|//       if a type cannot possibly be cated to another and by
comment|//       so doing predict the ClassCastException at run-time.
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|o
operator|.
name|getType
argument_list|(
name|cpg
argument_list|)
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitD2F
parameter_list|(
name|D2F
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|FLOAT
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitD2I
parameter_list|(
name|D2I
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|INT
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitD2L
parameter_list|(
name|D2L
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|LONG
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitDADD
parameter_list|(
name|DADD
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|DOUBLE
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitDALOAD
parameter_list|(
name|DALOAD
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|DOUBLE
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitDASTORE
parameter_list|(
name|DASTORE
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitDCMPG
parameter_list|(
name|DCMPG
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|INT
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitDCMPL
parameter_list|(
name|DCMPL
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|INT
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitDCONST
parameter_list|(
name|DCONST
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|DOUBLE
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitDDIV
parameter_list|(
name|DDIV
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|DOUBLE
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitDLOAD
parameter_list|(
name|DLOAD
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|DOUBLE
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitDMUL
parameter_list|(
name|DMUL
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|DOUBLE
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitDNEG
parameter_list|(
name|DNEG
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|DOUBLE
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitDREM
parameter_list|(
name|DREM
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|DOUBLE
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitDRETURN
parameter_list|(
name|DRETURN
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitDSTORE
parameter_list|(
name|DSTORE
name|o
parameter_list|)
block|{
name|locals
argument_list|()
operator|.
name|set
argument_list|(
name|o
operator|.
name|getIndex
argument_list|()
argument_list|,
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
argument_list|)
expr_stmt|;
name|locals
argument_list|()
operator|.
name|set
argument_list|(
name|o
operator|.
name|getIndex
argument_list|()
operator|+
literal|1
argument_list|,
name|Type
operator|.
name|UNKNOWN
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitDSUB
parameter_list|(
name|DSUB
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|DOUBLE
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitDUP
parameter_list|(
name|DUP
name|o
parameter_list|)
block|{
name|Type
name|t
init|=
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
decl_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|t
argument_list|)
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|t
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitDUP_X1
parameter_list|(
name|DUP_X1
name|o
parameter_list|)
block|{
name|Type
name|w1
init|=
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
decl_stmt|;
name|Type
name|w2
init|=
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
decl_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|w1
argument_list|)
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|w2
argument_list|)
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|w1
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitDUP_X2
parameter_list|(
name|DUP_X2
name|o
parameter_list|)
block|{
name|Type
name|w1
init|=
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
decl_stmt|;
name|Type
name|w2
init|=
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
decl_stmt|;
if|if
condition|(
name|w2
operator|.
name|getSize
argument_list|()
operator|==
literal|2
condition|)
block|{
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|w1
argument_list|)
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|w2
argument_list|)
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|w1
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|Type
name|w3
init|=
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
decl_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|w1
argument_list|)
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|w3
argument_list|)
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|w2
argument_list|)
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|w1
argument_list|)
expr_stmt|;
block|}
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitDUP2
parameter_list|(
name|DUP2
name|o
parameter_list|)
block|{
name|Type
name|t
init|=
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
decl_stmt|;
if|if
condition|(
name|t
operator|.
name|getSize
argument_list|()
operator|==
literal|2
condition|)
block|{
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|t
argument_list|)
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|t
argument_list|)
expr_stmt|;
block|}
else|else
block|{
comment|// t.getSize() is 1
name|Type
name|u
init|=
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
decl_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|u
argument_list|)
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|t
argument_list|)
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|u
argument_list|)
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|t
argument_list|)
expr_stmt|;
block|}
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitDUP2_X1
parameter_list|(
name|DUP2_X1
name|o
parameter_list|)
block|{
name|Type
name|t
init|=
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
decl_stmt|;
if|if
condition|(
name|t
operator|.
name|getSize
argument_list|()
operator|==
literal|2
condition|)
block|{
name|Type
name|u
init|=
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
decl_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|t
argument_list|)
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|u
argument_list|)
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|t
argument_list|)
expr_stmt|;
block|}
else|else
block|{
comment|//t.getSize() is1
name|Type
name|u
init|=
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
decl_stmt|;
name|Type
name|v
init|=
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
decl_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|u
argument_list|)
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|t
argument_list|)
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|v
argument_list|)
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|u
argument_list|)
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|t
argument_list|)
expr_stmt|;
block|}
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitDUP2_X2
parameter_list|(
name|DUP2_X2
name|o
parameter_list|)
block|{
name|Type
name|t
init|=
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
decl_stmt|;
if|if
condition|(
name|t
operator|.
name|getSize
argument_list|()
operator|==
literal|2
condition|)
block|{
name|Type
name|u
init|=
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
decl_stmt|;
if|if
condition|(
name|u
operator|.
name|getSize
argument_list|()
operator|==
literal|2
condition|)
block|{
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|t
argument_list|)
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|u
argument_list|)
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|t
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|Type
name|v
init|=
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
decl_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|t
argument_list|)
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|v
argument_list|)
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|u
argument_list|)
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|t
argument_list|)
expr_stmt|;
block|}
block|}
else|else
block|{
comment|//t.getSize() is 1
name|Type
name|u
init|=
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
decl_stmt|;
name|Type
name|v
init|=
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
decl_stmt|;
if|if
condition|(
name|v
operator|.
name|getSize
argument_list|()
operator|==
literal|2
condition|)
block|{
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|u
argument_list|)
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|t
argument_list|)
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|v
argument_list|)
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|u
argument_list|)
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|t
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|Type
name|w
init|=
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
decl_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|u
argument_list|)
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|t
argument_list|)
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|w
argument_list|)
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|v
argument_list|)
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|u
argument_list|)
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|t
argument_list|)
expr_stmt|;
block|}
block|}
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitF2D
parameter_list|(
name|F2D
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|DOUBLE
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitF2I
parameter_list|(
name|F2I
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|INT
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitF2L
parameter_list|(
name|F2L
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|LONG
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitFADD
parameter_list|(
name|FADD
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|FLOAT
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitFALOAD
parameter_list|(
name|FALOAD
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|FLOAT
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitFASTORE
parameter_list|(
name|FASTORE
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitFCMPG
parameter_list|(
name|FCMPG
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|INT
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitFCMPL
parameter_list|(
name|FCMPL
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|INT
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitFCONST
parameter_list|(
name|FCONST
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|FLOAT
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitFDIV
parameter_list|(
name|FDIV
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|FLOAT
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitFLOAD
parameter_list|(
name|FLOAD
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|FLOAT
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitFMUL
parameter_list|(
name|FMUL
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|FLOAT
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitFNEG
parameter_list|(
name|FNEG
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|FLOAT
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitFREM
parameter_list|(
name|FREM
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|FLOAT
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitFRETURN
parameter_list|(
name|FRETURN
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitFSTORE
parameter_list|(
name|FSTORE
name|o
parameter_list|)
block|{
name|locals
argument_list|()
operator|.
name|set
argument_list|(
name|o
operator|.
name|getIndex
argument_list|()
argument_list|,
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitFSUB
parameter_list|(
name|FSUB
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|FLOAT
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitGETFIELD
parameter_list|(
name|GETFIELD
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|Type
name|t
init|=
name|o
operator|.
name|getFieldType
argument_list|(
name|cpg
argument_list|)
decl_stmt|;
if|if
condition|(
name|t
operator|.
name|equals
argument_list|(
name|Type
operator|.
name|BOOLEAN
argument_list|)
operator|||
name|t
operator|.
name|equals
argument_list|(
name|Type
operator|.
name|CHAR
argument_list|)
operator|||
name|t
operator|.
name|equals
argument_list|(
name|Type
operator|.
name|BYTE
argument_list|)
operator|||
name|t
operator|.
name|equals
argument_list|(
name|Type
operator|.
name|SHORT
argument_list|)
condition|)
name|t
operator|=
name|Type
operator|.
name|INT
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|t
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitGETSTATIC
parameter_list|(
name|GETSTATIC
name|o
parameter_list|)
block|{
name|Type
name|t
init|=
name|o
operator|.
name|getFieldType
argument_list|(
name|cpg
argument_list|)
decl_stmt|;
if|if
condition|(
name|t
operator|.
name|equals
argument_list|(
name|Type
operator|.
name|BOOLEAN
argument_list|)
operator|||
name|t
operator|.
name|equals
argument_list|(
name|Type
operator|.
name|CHAR
argument_list|)
operator|||
name|t
operator|.
name|equals
argument_list|(
name|Type
operator|.
name|BYTE
argument_list|)
operator|||
name|t
operator|.
name|equals
argument_list|(
name|Type
operator|.
name|SHORT
argument_list|)
condition|)
name|t
operator|=
name|Type
operator|.
name|INT
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|t
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitGOTO
parameter_list|(
name|GOTO
name|o
parameter_list|)
block|{
comment|// no stack changes.
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitGOTO_W
parameter_list|(
name|GOTO_W
name|o
parameter_list|)
block|{
comment|// no stack changes.
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitI2B
parameter_list|(
name|I2B
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|INT
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitI2C
parameter_list|(
name|I2C
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|INT
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitI2D
parameter_list|(
name|I2D
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|DOUBLE
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitI2F
parameter_list|(
name|I2F
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|FLOAT
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitI2L
parameter_list|(
name|I2L
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|LONG
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitI2S
parameter_list|(
name|I2S
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|INT
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitIADD
parameter_list|(
name|IADD
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|INT
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitIALOAD
parameter_list|(
name|IALOAD
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|INT
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitIAND
parameter_list|(
name|IAND
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|INT
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitIASTORE
parameter_list|(
name|IASTORE
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitICONST
parameter_list|(
name|ICONST
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|INT
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitIDIV
parameter_list|(
name|IDIV
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|INT
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitIF_ACMPEQ
parameter_list|(
name|IF_ACMPEQ
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitIF_ACMPNE
parameter_list|(
name|IF_ACMPNE
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitIF_ICMPEQ
parameter_list|(
name|IF_ICMPEQ
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitIF_ICMPGE
parameter_list|(
name|IF_ICMPGE
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitIF_ICMPGT
parameter_list|(
name|IF_ICMPGT
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitIF_ICMPLE
parameter_list|(
name|IF_ICMPLE
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitIF_ICMPLT
parameter_list|(
name|IF_ICMPLT
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitIF_ICMPNE
parameter_list|(
name|IF_ICMPNE
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitIFEQ
parameter_list|(
name|IFEQ
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitIFGE
parameter_list|(
name|IFGE
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitIFGT
parameter_list|(
name|IFGT
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitIFLE
parameter_list|(
name|IFLE
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitIFLT
parameter_list|(
name|IFLT
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitIFNE
parameter_list|(
name|IFNE
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitIFNONNULL
parameter_list|(
name|IFNONNULL
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitIFNULL
parameter_list|(
name|IFNULL
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitIINC
parameter_list|(
name|IINC
name|o
parameter_list|)
block|{
comment|// stack is not changed.
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitILOAD
parameter_list|(
name|ILOAD
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|INT
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitIMUL
parameter_list|(
name|IMUL
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|INT
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitINEG
parameter_list|(
name|INEG
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|INT
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitINSTANCEOF
parameter_list|(
name|INSTANCEOF
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|INT
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitINVOKEINTERFACE
parameter_list|(
name|INVOKEINTERFACE
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
comment|//objectref
for|for
control|(
name|int
name|i
init|=
literal|0
init|;
name|i
operator|<
name|o
operator|.
name|getArgumentTypes
argument_list|(
name|cpg
argument_list|)
operator|.
name|length
condition|;
name|i
operator|++
control|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
block|}
comment|// We are sure the invoked method will xRETURN eventually
comment|// We simulate xRETURNs functionality here because we
comment|// don't really "jump into" and simulate the invoked
comment|// method.
if|if
condition|(
name|o
operator|.
name|getReturnType
argument_list|(
name|cpg
argument_list|)
operator|!=
name|Type
operator|.
name|VOID
condition|)
block|{
name|Type
name|t
init|=
name|o
operator|.
name|getReturnType
argument_list|(
name|cpg
argument_list|)
decl_stmt|;
if|if
condition|(
name|t
operator|.
name|equals
argument_list|(
name|Type
operator|.
name|BOOLEAN
argument_list|)
operator|||
name|t
operator|.
name|equals
argument_list|(
name|Type
operator|.
name|CHAR
argument_list|)
operator|||
name|t
operator|.
name|equals
argument_list|(
name|Type
operator|.
name|BYTE
argument_list|)
operator|||
name|t
operator|.
name|equals
argument_list|(
name|Type
operator|.
name|SHORT
argument_list|)
condition|)
name|t
operator|=
name|Type
operator|.
name|INT
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|t
argument_list|)
expr_stmt|;
block|}
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitINVOKESPECIAL
parameter_list|(
name|INVOKESPECIAL
name|o
parameter_list|)
block|{
if|if
condition|(
name|o
operator|.
name|getMethodName
argument_list|(
name|cpg
argument_list|)
operator|.
name|equals
argument_list|(
name|Constants
operator|.
name|CONSTRUCTOR_NAME
argument_list|)
condition|)
block|{
name|UninitializedObjectType
name|t
init|=
operator|(
name|UninitializedObjectType
operator|)
name|stack
argument_list|()
operator|.
name|peek
argument_list|(
name|o
operator|.
name|getArgumentTypes
argument_list|(
name|cpg
argument_list|)
operator|.
name|length
argument_list|)
decl_stmt|;
if|if
condition|(
name|t
operator|==
name|frame
operator|.
name|_this
condition|)
block|{
name|frame
operator|.
name|_this
operator|=
literal|null
expr_stmt|;
block|}
name|stack
argument_list|()
operator|.
name|initializeObject
argument_list|(
name|t
argument_list|)
expr_stmt|;
name|locals
argument_list|()
operator|.
name|initializeObject
argument_list|(
name|t
argument_list|)
expr_stmt|;
block|}
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
comment|//objectref
for|for
control|(
name|int
name|i
init|=
literal|0
init|;
name|i
operator|<
name|o
operator|.
name|getArgumentTypes
argument_list|(
name|cpg
argument_list|)
operator|.
name|length
condition|;
name|i
operator|++
control|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
block|}
comment|// We are sure the invoked method will xRETURN eventually
comment|// We simulate xRETURNs functionality here because we
comment|// don't really "jump into" and simulate the invoked
comment|// method.
if|if
condition|(
name|o
operator|.
name|getReturnType
argument_list|(
name|cpg
argument_list|)
operator|!=
name|Type
operator|.
name|VOID
condition|)
block|{
name|Type
name|t
init|=
name|o
operator|.
name|getReturnType
argument_list|(
name|cpg
argument_list|)
decl_stmt|;
if|if
condition|(
name|t
operator|.
name|equals
argument_list|(
name|Type
operator|.
name|BOOLEAN
argument_list|)
operator|||
name|t
operator|.
name|equals
argument_list|(
name|Type
operator|.
name|CHAR
argument_list|)
operator|||
name|t
operator|.
name|equals
argument_list|(
name|Type
operator|.
name|BYTE
argument_list|)
operator|||
name|t
operator|.
name|equals
argument_list|(
name|Type
operator|.
name|SHORT
argument_list|)
condition|)
name|t
operator|=
name|Type
operator|.
name|INT
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|t
argument_list|)
expr_stmt|;
block|}
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitINVOKESTATIC
parameter_list|(
name|INVOKESTATIC
name|o
parameter_list|)
block|{
for|for
control|(
name|int
name|i
init|=
literal|0
init|;
name|i
operator|<
name|o
operator|.
name|getArgumentTypes
argument_list|(
name|cpg
argument_list|)
operator|.
name|length
condition|;
name|i
operator|++
control|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
block|}
comment|// We are sure the invoked method will xRETURN eventually
comment|// We simulate xRETURNs functionality here because we
comment|// don't really "jump into" and simulate the invoked
comment|// method.
if|if
condition|(
name|o
operator|.
name|getReturnType
argument_list|(
name|cpg
argument_list|)
operator|!=
name|Type
operator|.
name|VOID
condition|)
block|{
name|Type
name|t
init|=
name|o
operator|.
name|getReturnType
argument_list|(
name|cpg
argument_list|)
decl_stmt|;
if|if
condition|(
name|t
operator|.
name|equals
argument_list|(
name|Type
operator|.
name|BOOLEAN
argument_list|)
operator|||
name|t
operator|.
name|equals
argument_list|(
name|Type
operator|.
name|CHAR
argument_list|)
operator|||
name|t
operator|.
name|equals
argument_list|(
name|Type
operator|.
name|BYTE
argument_list|)
operator|||
name|t
operator|.
name|equals
argument_list|(
name|Type
operator|.
name|SHORT
argument_list|)
condition|)
name|t
operator|=
name|Type
operator|.
name|INT
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|t
argument_list|)
expr_stmt|;
block|}
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitINVOKEVIRTUAL
parameter_list|(
name|INVOKEVIRTUAL
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
comment|//objectref
for|for
control|(
name|int
name|i
init|=
literal|0
init|;
name|i
operator|<
name|o
operator|.
name|getArgumentTypes
argument_list|(
name|cpg
argument_list|)
operator|.
name|length
condition|;
name|i
operator|++
control|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
block|}
comment|// We are sure the invoked method will xRETURN eventually
comment|// We simulate xRETURNs functionality here because we
comment|// don't really "jump into" and simulate the invoked
comment|// method.
if|if
condition|(
name|o
operator|.
name|getReturnType
argument_list|(
name|cpg
argument_list|)
operator|!=
name|Type
operator|.
name|VOID
condition|)
block|{
name|Type
name|t
init|=
name|o
operator|.
name|getReturnType
argument_list|(
name|cpg
argument_list|)
decl_stmt|;
if|if
condition|(
name|t
operator|.
name|equals
argument_list|(
name|Type
operator|.
name|BOOLEAN
argument_list|)
operator|||
name|t
operator|.
name|equals
argument_list|(
name|Type
operator|.
name|CHAR
argument_list|)
operator|||
name|t
operator|.
name|equals
argument_list|(
name|Type
operator|.
name|BYTE
argument_list|)
operator|||
name|t
operator|.
name|equals
argument_list|(
name|Type
operator|.
name|SHORT
argument_list|)
condition|)
name|t
operator|=
name|Type
operator|.
name|INT
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|t
argument_list|)
expr_stmt|;
block|}
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitIOR
parameter_list|(
name|IOR
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|INT
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitIREM
parameter_list|(
name|IREM
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|INT
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitIRETURN
parameter_list|(
name|IRETURN
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitISHL
parameter_list|(
name|ISHL
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|INT
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitISHR
parameter_list|(
name|ISHR
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|INT
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitISTORE
parameter_list|(
name|ISTORE
name|o
parameter_list|)
block|{
name|locals
argument_list|()
operator|.
name|set
argument_list|(
name|o
operator|.
name|getIndex
argument_list|()
argument_list|,
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitISUB
parameter_list|(
name|ISUB
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|INT
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitIUSHR
parameter_list|(
name|IUSHR
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|INT
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitIXOR
parameter_list|(
name|IXOR
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|INT
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitJSR
parameter_list|(
name|JSR
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|push
argument_list|(
operator|new
name|ReturnaddressType
argument_list|(
name|o
operator|.
name|physicalSuccessor
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
comment|//System.err.println("TODO-----------:"+o.physicalSuccessor());
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitJSR_W
parameter_list|(
name|JSR_W
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|push
argument_list|(
operator|new
name|ReturnaddressType
argument_list|(
name|o
operator|.
name|physicalSuccessor
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitL2D
parameter_list|(
name|L2D
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|DOUBLE
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitL2F
parameter_list|(
name|L2F
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|FLOAT
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitL2I
parameter_list|(
name|L2I
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|INT
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitLADD
parameter_list|(
name|LADD
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|LONG
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitLALOAD
parameter_list|(
name|LALOAD
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|LONG
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitLAND
parameter_list|(
name|LAND
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|LONG
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitLASTORE
parameter_list|(
name|LASTORE
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitLCMP
parameter_list|(
name|LCMP
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|INT
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitLCONST
parameter_list|(
name|LCONST
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|LONG
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitLDC
parameter_list|(
name|LDC
name|o
parameter_list|)
block|{
name|Constant
name|c
init|=
name|cpg
operator|.
name|getConstant
argument_list|(
name|o
operator|.
name|getIndex
argument_list|()
argument_list|)
decl_stmt|;
if|if
condition|(
name|c
operator|instanceof
name|ConstantInteger
condition|)
block|{
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|INT
argument_list|)
expr_stmt|;
block|}
if|if
condition|(
name|c
operator|instanceof
name|ConstantFloat
condition|)
block|{
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|FLOAT
argument_list|)
expr_stmt|;
block|}
if|if
condition|(
name|c
operator|instanceof
name|ConstantString
condition|)
block|{
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|STRING
argument_list|)
expr_stmt|;
block|}
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitLDC_W
parameter_list|(
name|LDC_W
name|o
parameter_list|)
block|{
name|Constant
name|c
init|=
name|cpg
operator|.
name|getConstant
argument_list|(
name|o
operator|.
name|getIndex
argument_list|()
argument_list|)
decl_stmt|;
if|if
condition|(
name|c
operator|instanceof
name|ConstantInteger
condition|)
block|{
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|INT
argument_list|)
expr_stmt|;
block|}
if|if
condition|(
name|c
operator|instanceof
name|ConstantFloat
condition|)
block|{
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|FLOAT
argument_list|)
expr_stmt|;
block|}
if|if
condition|(
name|c
operator|instanceof
name|ConstantString
condition|)
block|{
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|STRING
argument_list|)
expr_stmt|;
block|}
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitLDC2_W
parameter_list|(
name|LDC2_W
name|o
parameter_list|)
block|{
name|Constant
name|c
init|=
name|cpg
operator|.
name|getConstant
argument_list|(
name|o
operator|.
name|getIndex
argument_list|()
argument_list|)
decl_stmt|;
if|if
condition|(
name|c
operator|instanceof
name|ConstantLong
condition|)
block|{
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|LONG
argument_list|)
expr_stmt|;
block|}
if|if
condition|(
name|c
operator|instanceof
name|ConstantDouble
condition|)
block|{
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|DOUBLE
argument_list|)
expr_stmt|;
block|}
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitLDIV
parameter_list|(
name|LDIV
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|LONG
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitLLOAD
parameter_list|(
name|LLOAD
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|locals
argument_list|()
operator|.
name|get
argument_list|(
name|o
operator|.
name|getIndex
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitLMUL
parameter_list|(
name|LMUL
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|LONG
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitLNEG
parameter_list|(
name|LNEG
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|LONG
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitLOOKUPSWITCH
parameter_list|(
name|LOOKUPSWITCH
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
comment|//key
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitLOR
parameter_list|(
name|LOR
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|LONG
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitLREM
parameter_list|(
name|LREM
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|LONG
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitLRETURN
parameter_list|(
name|LRETURN
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitLSHL
parameter_list|(
name|LSHL
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|LONG
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitLSHR
parameter_list|(
name|LSHR
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|LONG
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitLSTORE
parameter_list|(
name|LSTORE
name|o
parameter_list|)
block|{
name|locals
argument_list|()
operator|.
name|set
argument_list|(
name|o
operator|.
name|getIndex
argument_list|()
argument_list|,
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
argument_list|)
expr_stmt|;
name|locals
argument_list|()
operator|.
name|set
argument_list|(
name|o
operator|.
name|getIndex
argument_list|()
operator|+
literal|1
argument_list|,
name|Type
operator|.
name|UNKNOWN
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitLSUB
parameter_list|(
name|LSUB
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|LONG
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitLUSHR
parameter_list|(
name|LUSHR
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|LONG
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitLXOR
parameter_list|(
name|LXOR
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|LONG
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitMONITORENTER
parameter_list|(
name|MONITORENTER
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitMONITOREXIT
parameter_list|(
name|MONITOREXIT
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitMULTIANEWARRAY
parameter_list|(
name|MULTIANEWARRAY
name|o
parameter_list|)
block|{
for|for
control|(
name|int
name|i
init|=
literal|0
init|;
name|i
operator|<
name|o
operator|.
name|getDimensions
argument_list|()
condition|;
name|i
operator|++
control|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
block|}
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|o
operator|.
name|getType
argument_list|(
name|cpg
argument_list|)
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitNEW
parameter_list|(
name|NEW
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|push
argument_list|(
operator|new
name|UninitializedObjectType
argument_list|(
operator|(
name|ObjectType
operator|)
operator|(
name|o
operator|.
name|getType
argument_list|(
name|cpg
argument_list|)
operator|)
argument_list|)
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitNEWARRAY
parameter_list|(
name|NEWARRAY
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|o
operator|.
name|getType
argument_list|()
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitNOP
parameter_list|(
name|NOP
name|o
parameter_list|)
block|{
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitPOP
parameter_list|(
name|POP
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitPOP2
parameter_list|(
name|POP2
name|o
parameter_list|)
block|{
name|Type
name|t
init|=
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
decl_stmt|;
if|if
condition|(
name|t
operator|.
name|getSize
argument_list|()
operator|==
literal|1
condition|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
block|}
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitPUTFIELD
parameter_list|(
name|PUTFIELD
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitPUTSTATIC
parameter_list|(
name|PUTSTATIC
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitRET
parameter_list|(
name|RET
name|o
parameter_list|)
block|{
comment|// do nothing, return address
comment|// is in in the local variables.
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitRETURN
parameter_list|(
name|RETURN
name|o
parameter_list|)
block|{
comment|// do nothing.
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitSALOAD
parameter_list|(
name|SALOAD
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|INT
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitSASTORE
parameter_list|(
name|SASTORE
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitSIPUSH
parameter_list|(
name|SIPUSH
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|Type
operator|.
name|INT
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitSWAP
parameter_list|(
name|SWAP
name|o
parameter_list|)
block|{
name|Type
name|t
init|=
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
decl_stmt|;
name|Type
name|u
init|=
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
decl_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|t
argument_list|)
expr_stmt|;
name|stack
argument_list|()
operator|.
name|push
argument_list|(
name|u
argument_list|)
expr_stmt|;
block|}
comment|/** Symbolically executes the corresponding Java Virtual Machine instruction. */
specifier|public
name|void
name|visitTABLESWITCH
parameter_list|(
name|TABLESWITCH
name|o
parameter_list|)
block|{
name|stack
argument_list|()
operator|.
name|pop
argument_list|()
expr_stmt|;
block|}
block|}
end_class

end_unit

