begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|bcel
package|;
end_package

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|bcel
operator|.
name|classfile
operator|.
name|JavaClass
import|;
end_import

begin_class
specifier|public
class|class
name|AnnotationAccessFlagTestCase
extends|extends
name|AbstractTestCase
block|{
comment|/** 	 * If you write an annotation and compile it, the class file generated 	 * should be marked as an annotation type - which is detectable through 	 * BCEL. 	 */
specifier|public
name|void
name|testAnnotationClassSaysItIs
parameter_list|()
throws|throws
name|ClassNotFoundException
block|{
name|JavaClass
name|clazz
init|=
name|getTestClass
argument_list|(
literal|"org.apache.bcel.data.SimpleAnnotation"
argument_list|)
decl_stmt|;
name|assertTrue
argument_list|(
literal|"Expected SimpleAnnotation class to say it was an annotation - but it didn't !"
argument_list|,
name|clazz
operator|.
name|isAnnotation
argument_list|()
argument_list|)
expr_stmt|;
name|clazz
operator|=
name|getTestClass
argument_list|(
literal|"org.apache.bcel.data.SimpleClass"
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
literal|"Expected SimpleClass class to say it was not an annotation - but it didn't !"
argument_list|,
operator|!
name|clazz
operator|.
name|isAnnotation
argument_list|()
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

