begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *   http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|bcel
operator|.
name|verifier
package|;
end_package

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|jupiter
operator|.
name|api
operator|.
name|Disabled
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|jupiter
operator|.
name|params
operator|.
name|ParameterizedTest
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|jupiter
operator|.
name|params
operator|.
name|provider
operator|.
name|MethodSource
import|;
end_import

begin_class
specifier|public
class|class
name|VerifyJavaHomesTestCase
extends|extends
name|AbstractVerifierTestCase
block|{
specifier|static
name|int
name|count
decl_stmt|;
comment|/**      * Eventually runs out of memory? Super now calls VerifierFactory.clear();      *       *<pre>       164800................................................................................       165600...........Exception in thread "fork-1-event-thread" .java.lang.OutOfMemoryError: Java heap space         Exception in thread "fork-1-event-thread" java.lang.OutOfMemoryError: Java heap space         at java.lang.AbstractStringBuilder.<init>(AbstractStringBuilder.java:68)         at java.lang.StringBuilder.<init>(StringBuilder.java:106)         at org.apache.maven.surefire.api.stream.AbstractStreamDecoder.toString(AbstractStreamDecoder.java:364)         at org.apache.maven.surefire.api.stream.AbstractStreamDecoder.readString(AbstractStreamDecoder.java:336)         at org.apache.maven.surefire.api.stream.AbstractStreamDecoder.readString(AbstractStreamDecoder.java:196)         at org.apache.maven.surefire.stream.EventDecoder.decode(EventDecoder.java:176)         at org.apache.maven.plugin.surefire.extensions.EventConsumerThread.run(EventConsumerThread.java:73)      *</pre>      *       * @param name      * @throws ClassNotFoundException      */
annotation|@
name|Disabled
argument_list|(
literal|"Run once in a while, it takes a very long time."
argument_list|)
annotation|@
name|ParameterizedTest
comment|// @Execution(ExecutionMode.CONCURRENT)
annotation|@
name|MethodSource
argument_list|(
literal|"org.apache.bcel.generic.JavaHome#streamJarEntryClassName"
argument_list|)
specifier|public
name|void
name|testJarEntryClassName
parameter_list|(
specifier|final
name|String
name|name
parameter_list|)
throws|throws
name|ClassNotFoundException
block|{
comment|// System.out.println(jarEntry.getName());
comment|// Skip $ classes for now
name|count
operator|++
expr_stmt|;
if|if
condition|(
name|count
operator|%
literal|10
operator|==
literal|0
condition|)
block|{
name|System
operator|.
name|out
operator|.
name|print
argument_list|(
literal|'.'
argument_list|)
expr_stmt|;
block|}
if|if
condition|(
name|count
operator|%
literal|800
operator|==
literal|0
condition|)
block|{
name|System
operator|.
name|out
operator|.
name|println
argument_list|()
expr_stmt|;
name|System
operator|.
name|out
operator|.
name|print
argument_list|(
name|count
argument_list|)
expr_stmt|;
block|}
if|if
condition|(
operator|!
name|name
operator|.
name|contains
argument_list|(
literal|"$"
argument_list|)
condition|)
block|{
name|doAllPasses
argument_list|(
name|name
argument_list|)
expr_stmt|;
block|}
block|}
block|}
end_class

end_unit

