begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|bcel
operator|.
name|verifier
operator|.
name|statics
package|;
end_package

begin_comment
comment|/* ====================================================================  * The Apache Software License, Version 1.1  *  * Copyright (c) 2001 The Apache Software Foundation.  All rights  * reserved.  *  * Redistribution and use in source and binary forms, with or without  * modification, are permitted provided that the following conditions  * are met:  *  * 1. Redistributions of source code must retain the above copyright  *    notice, this list of conditions and the following disclaimer.  *  * 2. Redistributions in binary form must reproduce the above copyright  *    notice, this list of conditions and the following disclaimer in  *    the documentation and/or other materials provided with the  *    distribution.  *  * 3. The end-user documentation included with the redistribution,  *    if any, must include the following acknowledgment:  *       "This product includes software developed by the  *        Apache Software Foundation (http://www.apache.org/)."  *    Alternately, this acknowledgment may appear in the software itself,  *    if and wherever such third-party acknowledgments normally appear.  *  * 4. The names "Apache" and "Apache Software Foundation" and  *    "Apache BCEL" must not be used to endorse or promote products  *    derived from this software without prior written permission. For  *    written permission, please contact apache@apache.org.  *  * 5. Products derived from this software may not be called "Apache",  *    "Apache BCEL", nor may "Apache" appear in their name, without  *    prior written permission of the Apache Software Foundation.  *  * THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESSED OR IMPLIED  * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES  * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE  * DISCLAIMED.  IN NO EVENT SHALL THE APACHE SOFTWARE FOUNDATION OR  * ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,  * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT  * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF  * USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND  * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,  * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT  * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF  * SUCH DAMAGE.  * ====================================================================  *  * This software consists of voluntary contributions made by many  * individuals on behalf of the Apache Software Foundation.  For more  * information on the Apache Software Foundation, please see  *<http://www.apache.org/>.  */
end_comment

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|bcel
operator|.
name|Constants
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|bcel
operator|.
name|generic
operator|.
name|Type
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|bcel
operator|.
name|verifier
operator|.
name|exc
operator|.
name|*
import|;
end_import

begin_comment
comment|/**  * A utility class holding the information about  * the names and the types of the local variables in  * a given method.  *  * @version $Id$  * @author<A HREF="http://www.inf.fu-berlin.de/~ehaase"/>Enver Haase</A>  */
end_comment

begin_class
specifier|public
class|class
name|LocalVariablesInfo
block|{
comment|/** The information about the local variables is stored here. */
specifier|private
name|LocalVariableInfo
index|[]
name|localVariableInfos
decl_stmt|;
comment|/** 	 * The ints in the list represent code offsets where either instructions must start 	 * or the offset is the length of the code array. This will be verified in Pass 3a. 	 */
specifier|private
name|IntList
name|instruction_offsets
init|=
operator|new
name|IntList
argument_list|()
decl_stmt|;
comment|/** The constructor. */
name|LocalVariablesInfo
parameter_list|(
name|int
name|max_locals
parameter_list|)
block|{
name|localVariableInfos
operator|=
operator|new
name|LocalVariableInfo
index|[
name|max_locals
index|]
expr_stmt|;
for|for
control|(
name|int
name|i
init|=
literal|0
init|;
name|i
operator|<
name|max_locals
condition|;
name|i
operator|++
control|)
block|{
name|localVariableInfos
index|[
name|i
index|]
operator|=
operator|new
name|LocalVariableInfo
argument_list|()
expr_stmt|;
block|}
block|}
comment|/** Returns the LocalVariableInfo for the given slot. */
specifier|public
name|LocalVariableInfo
name|getLocalVariableInfo
parameter_list|(
name|int
name|slot
parameter_list|)
block|{
if|if
condition|(
name|slot
operator|<
literal|0
operator|||
name|slot
operator|>=
name|localVariableInfos
operator|.
name|length
condition|)
block|{
throw|throw
operator|new
name|AssertionViolatedException
argument_list|(
literal|"Slot number for local variable information out of range."
argument_list|)
throw|;
block|}
return|return
name|localVariableInfos
index|[
name|slot
index|]
return|;
block|}
comment|/** 	 * Adds information about the local variable in slot 'slot'. Automatically  	 * adds information for slot+1 if 't' is Type.LONG or Type.DOUBLE. 	 * @throws LocalVariableInfoInconsistentException if the new information conflicts 	 *         with already gathered information. 	 */
specifier|public
name|void
name|add
parameter_list|(
name|int
name|slot
parameter_list|,
name|String
name|name
parameter_list|,
name|int
name|startpc
parameter_list|,
name|int
name|length
parameter_list|,
name|Type
name|t
parameter_list|)
throws|throws
name|LocalVariableInfoInconsistentException
block|{
comment|// The add operation on LocalVariableInfo may throw the '...Inconsistent...' exception, we don't throw it explicitely here.
if|if
condition|(
name|slot
operator|<
literal|0
operator|||
name|slot
operator|>=
name|localVariableInfos
operator|.
name|length
condition|)
block|{
throw|throw
operator|new
name|AssertionViolatedException
argument_list|(
literal|"Slot number for local variable information out of range."
argument_list|)
throw|;
block|}
name|localVariableInfos
index|[
name|slot
index|]
operator|.
name|add
argument_list|(
name|name
argument_list|,
name|startpc
argument_list|,
name|length
argument_list|,
name|t
argument_list|)
expr_stmt|;
if|if
condition|(
name|t
operator|==
name|Type
operator|.
name|LONG
condition|)
name|localVariableInfos
index|[
name|slot
operator|+
literal|1
index|]
operator|.
name|add
argument_list|(
name|name
argument_list|,
name|startpc
argument_list|,
name|length
argument_list|,
name|LONG_Upper
operator|.
name|theInstance
argument_list|()
argument_list|)
expr_stmt|;
if|if
condition|(
name|t
operator|==
name|Type
operator|.
name|DOUBLE
condition|)
name|localVariableInfos
index|[
name|slot
operator|+
literal|1
index|]
operator|.
name|add
argument_list|(
name|name
argument_list|,
name|startpc
argument_list|,
name|length
argument_list|,
name|DOUBLE_Upper
operator|.
name|theInstance
argument_list|()
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

