begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|bcel
operator|.
name|classfile
package|;
end_package

begin_comment
comment|/* ====================================================================  * The Apache Software License, Version 1.1  *  * Copyright (c) 2001 The Apache Software Foundation.  All rights  * reserved.  *  * Redistribution and use in source and binary forms, with or without  * modification, are permitted provided that the following conditions  * are met:  *  * 1. Redistributions of source code must retain the above copyright  *    notice, this list of conditions and the following disclaimer.  *  * 2. Redistributions in binary form must reproduce the above copyright  *    notice, this list of conditions and the following disclaimer in  *    the documentation and/or other materials provided with the  *    distribution.  *  * 3. The end-user documentation included with the redistribution,  *    if any, must include the following acknowledgment:  *       "This product includes software developed by the  *        Apache Software Foundation (http://www.apache.org/)."  *    Alternately, this acknowledgment may appear in the software itself,  *    if and wherever such third-party acknowledgments normally appear.  *  * 4. The names "Apache" and "Apache Software Foundation" and  *    "Apache BCEL" must not be used to endorse or promote products  *    derived from this software without prior written permission. For  *    written permission, please contact apache@apache.org.  *  * 5. Products derived from this software may not be called "Apache",  *    "Apache BCEL", nor may "Apache" appear in their name, without  *    prior written permission of the Apache Software Foundation.  *  * THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESSED OR IMPLIED  * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES  * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE  * DISCLAIMED.  IN NO EVENT SHALL THE APACHE SOFTWARE FOUNDATION OR  * ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,  * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT  * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF  * USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND  * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,  * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT  * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF  * SUCH DAMAGE.  * ====================================================================  *  * This software consists of voluntary contributions made by many  * individuals on behalf of the Apache Software Foundation.  For more  * information on the Apache Software Foundation, please see  *<http://www.apache.org/>.  */
end_comment

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|bcel
operator|.
name|Constants
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|*
import|;
end_import

begin_comment
comment|/**  * This class represents an entry in the exception table of the<em>Code</em>  * attribute and is used only there. It contains a range in which a  * particular exception handler is active.  *  * @version $Id$  * @author<A HREF="mailto:markus.dahm@berlin.de">M. Dahm</A>  * @see     Code  */
end_comment

begin_class
specifier|public
specifier|final
class|class
name|CodeException
implements|implements
name|Cloneable
implements|,
name|Constants
implements|,
name|Node
block|{
specifier|private
name|int
name|start_pc
decl_stmt|;
comment|// Range in the code the exception handler is
specifier|private
name|int
name|end_pc
decl_stmt|;
comment|// active. start_pc is inclusive, end_pc exclusive
specifier|private
name|int
name|handler_pc
decl_stmt|;
comment|/* Starting address of exception handler, i.e., 			   * an offset from start of code. 			   */
specifier|private
name|int
name|catch_type
decl_stmt|;
comment|/* If this is zero the handler catches any 			   * exception, otherwise it points to the 			   * exception class which is to be caught. 			   */
comment|/**    * Initialize from another object.    */
specifier|public
name|CodeException
parameter_list|(
name|CodeException
name|c
parameter_list|)
block|{
name|this
argument_list|(
name|c
operator|.
name|getStartPC
argument_list|()
argument_list|,
name|c
operator|.
name|getEndPC
argument_list|()
argument_list|,
name|c
operator|.
name|getHandlerPC
argument_list|()
argument_list|,
name|c
operator|.
name|getCatchType
argument_list|()
argument_list|)
expr_stmt|;
block|}
comment|/**    * Construct object from file stream.    * @param file Input stream    * @throws IOException    */
name|CodeException
parameter_list|(
name|DataInputStream
name|file
parameter_list|)
throws|throws
name|IOException
block|{
name|this
argument_list|(
name|file
operator|.
name|readUnsignedShort
argument_list|()
argument_list|,
name|file
operator|.
name|readUnsignedShort
argument_list|()
argument_list|,
name|file
operator|.
name|readUnsignedShort
argument_list|()
argument_list|,
name|file
operator|.
name|readUnsignedShort
argument_list|()
argument_list|)
expr_stmt|;
block|}
comment|/**    * @param start_pc Range in the code the exception handler is active,    * start_pc is inclusive while    * @param end_pc is exclusive    * @param handler_pc Starting address of exception handler, i.e.,    * an offset from start of code.    * @param catch_type If zero the handler catches any     * exception, otherwise it points to the exception class which is     * to be caught.    */
specifier|public
name|CodeException
parameter_list|(
name|int
name|start_pc
parameter_list|,
name|int
name|end_pc
parameter_list|,
name|int
name|handler_pc
parameter_list|,
name|int
name|catch_type
parameter_list|)
block|{
name|this
operator|.
name|start_pc
operator|=
name|start_pc
expr_stmt|;
name|this
operator|.
name|end_pc
operator|=
name|end_pc
expr_stmt|;
name|this
operator|.
name|handler_pc
operator|=
name|handler_pc
expr_stmt|;
name|this
operator|.
name|catch_type
operator|=
name|catch_type
expr_stmt|;
block|}
comment|/**    * Called by objects that are traversing the nodes of the tree implicitely    * defined by the contents of a Java class. I.e., the hierarchy of methods,    * fields, attributes, etc. spawns a tree of objects.    *    * @param v Visitor object    */
specifier|public
name|void
name|accept
parameter_list|(
name|Visitor
name|v
parameter_list|)
block|{
name|v
operator|.
name|visitCodeException
argument_list|(
name|this
argument_list|)
expr_stmt|;
block|}
comment|/**    * Dump code exception to file stream in binary format.    *    * @param file Output file stream    * @throws IOException    */
specifier|public
specifier|final
name|void
name|dump
parameter_list|(
name|DataOutputStream
name|file
parameter_list|)
throws|throws
name|IOException
block|{
name|file
operator|.
name|writeShort
argument_list|(
name|start_pc
argument_list|)
expr_stmt|;
name|file
operator|.
name|writeShort
argument_list|(
name|end_pc
argument_list|)
expr_stmt|;
name|file
operator|.
name|writeShort
argument_list|(
name|handler_pc
argument_list|)
expr_stmt|;
name|file
operator|.
name|writeShort
argument_list|(
name|catch_type
argument_list|)
expr_stmt|;
block|}
comment|/**    * @return 0, if the handler catches any exception, otherwise it points to    * the exception class which is to be caught.    */
specifier|public
specifier|final
name|int
name|getCatchType
parameter_list|()
block|{
return|return
name|catch_type
return|;
block|}
comment|/**    * @return Exclusive end index of the region where the handler is active.    */
specifier|public
specifier|final
name|int
name|getEndPC
parameter_list|()
block|{
return|return
name|end_pc
return|;
block|}
comment|/**    * @return Starting address of exception handler, relative to the code.    */
specifier|public
specifier|final
name|int
name|getHandlerPC
parameter_list|()
block|{
return|return
name|handler_pc
return|;
block|}
comment|/**    * @return Inclusive start index of the region where the handler is active.    */
specifier|public
specifier|final
name|int
name|getStartPC
parameter_list|()
block|{
return|return
name|start_pc
return|;
block|}
comment|/**    * @param catch_type.    */
specifier|public
specifier|final
name|void
name|setCatchType
parameter_list|(
name|int
name|catch_type
parameter_list|)
block|{
name|this
operator|.
name|catch_type
operator|=
name|catch_type
expr_stmt|;
block|}
comment|/**    * @param end_pc end of handled block    */
specifier|public
specifier|final
name|void
name|setEndPC
parameter_list|(
name|int
name|end_pc
parameter_list|)
block|{
name|this
operator|.
name|end_pc
operator|=
name|end_pc
expr_stmt|;
block|}
comment|/**    * @param handler_pc where the actual code is    */
specifier|public
specifier|final
name|void
name|setHandlerPC
parameter_list|(
name|int
name|handler_pc
parameter_list|)
block|{
name|this
operator|.
name|handler_pc
operator|=
name|handler_pc
expr_stmt|;
block|}
comment|/**    * @param start_pc start of handled block    */
specifier|public
specifier|final
name|void
name|setStartPC
parameter_list|(
name|int
name|start_pc
parameter_list|)
block|{
name|this
operator|.
name|start_pc
operator|=
name|start_pc
expr_stmt|;
block|}
comment|/**    * @return String representation.    */
specifier|public
specifier|final
name|String
name|toString
parameter_list|()
block|{
return|return
literal|"CodeException(start_pc = "
operator|+
name|start_pc
operator|+
literal|", end_pc = "
operator|+
name|end_pc
operator|+
literal|", handler_pc = "
operator|+
name|handler_pc
operator|+
literal|", catch_type = "
operator|+
name|catch_type
operator|+
literal|")"
return|;
block|}
comment|/**    * @return String representation.    */
specifier|public
specifier|final
name|String
name|toString
parameter_list|(
name|ConstantPool
name|cp
parameter_list|,
name|boolean
name|verbose
parameter_list|)
block|{
name|String
name|str
decl_stmt|;
if|if
condition|(
name|catch_type
operator|==
literal|0
condition|)
name|str
operator|=
literal|"<Any exception>(0)"
expr_stmt|;
else|else
name|str
operator|=
name|Utility
operator|.
name|compactClassName
argument_list|(
name|cp
operator|.
name|getConstantString
argument_list|(
name|catch_type
argument_list|,
name|CONSTANT_Class
argument_list|)
argument_list|,
literal|false
argument_list|)
operator|+
operator|(
name|verbose
condition|?
literal|"("
operator|+
name|catch_type
operator|+
literal|")"
else|:
literal|""
operator|)
expr_stmt|;
return|return
name|start_pc
operator|+
literal|"\t"
operator|+
name|end_pc
operator|+
literal|"\t"
operator|+
name|handler_pc
operator|+
literal|"\t"
operator|+
name|str
return|;
block|}
specifier|public
specifier|final
name|String
name|toString
parameter_list|(
name|ConstantPool
name|cp
parameter_list|)
block|{
return|return
name|toString
argument_list|(
name|cp
argument_list|,
literal|true
argument_list|)
return|;
block|}
comment|/**    * @return deep copy of this object    */
specifier|public
name|CodeException
name|copy
parameter_list|()
block|{
try|try
block|{
return|return
operator|(
name|CodeException
operator|)
name|clone
argument_list|()
return|;
block|}
catch|catch
parameter_list|(
name|CloneNotSupportedException
name|e
parameter_list|)
block|{
block|}
return|return
literal|null
return|;
block|}
block|}
end_class

end_unit

